# Generated by Django 4.0.4 on 2022-04-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_car_sell', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registervehicle',
            old_name='Vehicle_Availablity',
            new_name='vehicle_availablity',
        ),
        migrations.AddField(
            model_name='contactus',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
